#!/bin/sh -e

rm /etc/rockpi-quad.env > /dev/null || true

systemctl stop rockpi-quad.service
systemctl disable rockpi-quad.service

if [ -d /run/systemd/system ]; then
  systemctl --system daemon-reload > /dev/null || true
fi

rm -rf /usr/bin/rockpi-quad/__pycache__
