#!/bin/sh -e

checkReboot(){
  echo Installation will take effect after reboot!!!
}

if [ "$(python3 -c 'import sys; print(f"{sys.version_info.minor >= 11}")')" = "True" ]; then
  pip3 install adafruit-circuitpython-ssd1306 --break-system-packages
else
  pip3 install adafruit-circuitpython-ssd1306
fi

systemctl enable rockpi-penta.service

model=$(tr -d '\0' </proc/device-tree/model)

case "$model" in
*"Raspberry Pi 5"*)
  raspi-config nonint do_i2c 0 >/dev/null || true
  cp /usr/bin/rockpi-penta/env/rpi5.env /etc/rockpi-penta.env
  systemctl start rockpi-penta.service
  ;;
*"Raspberry Pi 4"*)
  raspi-config nonint do_i2c 0 >/dev/null || true
  mv /usr/bin/rockpi-penta/env/rpi4.env /etc/rockpi-penta.env
  systemctl start rockpi-penta.service
  ;;
*"ROCK 5"*)
  mv /boot/dtbo/rk3588-i2c8-m2.dtbo.disabled /boot/dtbo/rk3588-i2c8-m2.dtbo || true
  mv /boot/dtbo/rk3588-pwm14-m1.dtbo.disabled /boot/dtbo/rk3588-pwm14-m1.dtbo.dtbo || true
  cp /usr/bin/rockpi-penta/env/rock_5a.env /etc/rockpi-penta.env
  u-boot-update || true
  checkReboot
  ;;
*"ROCK3 Model C"*)
  mv /boot/dtbo/rk3568-i2c3-m0.dtbo.disabled /boot/dtbo/rk3568-i2c3-m0.dtbo || true
  cp /usr/bin/rockpi-penta/env/rock_3c.env /etc/rockpi-penta.env
  u-boot-update || true
  checkReboot
  ;;
*"ROCK3 Model A"*)
  mv /boot/dtbo/rk3568-i2c3-m0.dtbo.disabled /boot/dtbo/rk3568-i2c3-m0.dtbo || true
  mv /boot/dtbo/rk3568-pwm15-m0.dtbo.disabled /boot/dtbo/rk3568-pwm15-m0.dtbo || true
  cp /usr/bin/rockpi-penta/env/rock_pi_3.env /etc/rockpi-penta.env
  u-boot-update || true
  checkReboot
  ;;
*"Radxa ROCK 4SE"* | *"ROCK Pi 4"*)
  mv /boot/dtbo/rk3399-i2c7.dtbo.disabled /boot/dtbo/rk3399-i2c7.dtbo || true
  mv /boot/dtbo/rk3399-pwm1.dtbo.disabled /boot/dtbo/rk3399-pwm1.dtbo || true
  cp /usr/bin/rockpi-penta/env/rock_pi_4.env /etc/rockpi-penta.env
  u-boot-update || true
  checkReboot
  ;;
*)
  echo Not support in your board.
  exit 2
  ;;
esac
