#!/bin/sh -e

rm /etc/rockpi-penta.env > /dev/null || true

systemctl stop rockpi-penta.service
systemctl disable rockpi-penta.service

if [ -d /run/systemd/system ]; then
  systemctl --system daemon-reload > /dev/null || true
fi

rm -rf /usr/bin/rockpi-penta/__pycache__
