#!/bin/sh
set -e

systemctl enable rockpi-penta.service

if [ -d /run/systemd/system ]; then
  systemctl --system daemon-reload > /dev/null || true
fi

systemctl start rockpi-penta.service > /dev/null
